import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import {ThemeProvider} from "@/components/theme-providers";
import {Toaster} from "@/components/ui/toaster";
import {cn} from "@/lib/utils";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
	title: "Splitwise App",
	description: "Generated by create next app",
};

export default async function RootLayout(
	{
		children,
	}: Readonly<{
		children: React.ReactNode;
	}>) {
	
	
	return (
		<html lang="en" suppressHydrationWarning={true}>
		<body className={cn(inter.className)}>
		<ThemeProvider
			attribute="class"
			defaultTheme="light"
			enableSystem={true}
			disableTransitionOnChange>
			{children}
			<Toaster/>
		</ThemeProvider>
		</body>
		</html>
	);
}
